name: 'Smartrr'
description: 'Automatically add Pull Request reviewers based on changed files.'
author: 'Uchenna Sylvester Okoro'

inputs:
  github-token:
    description: 'The GitHub token to use for authentication'
    required: true
  max-reviewers:
    description: 'The maximum number of reviewers to add to a Pull Request'
    required: false
    default: '2'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'bookmark'
  color: 'green'
