name: 'Label PRs'

on:
  pull_request:
    types: [opened]

defaults:
  run:
    shell: 'bash'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: Add label to PR
        uses: UcheSylvester/pr-labelr@v0.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
