name: Lint
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

defaults:
  run:
    shell: 'bash'

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Setup node'
        uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - name: Install dependencies
        run: pnpm install

      - run: yarn lint
