name: main

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Smartrr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Auto PR review requests
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          max-reviewers: 2
