name: main

on:
  pull_request:
    types: [opened]

defaults:
  run:
    shell: 'bash'

jobs:
  Smartrr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Auto PR review requests
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          max-reviewers: 2
