name: main

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Smartrr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Auto PR review requests
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
